# ========== Profile ========== #
# avatar
avatar: https://pic.qqtn.com/up/2017-11/15102951604705106.jpg
# author name
author: hello-me
# signature
signature:
# SNS
social:
  email: hello_world321@sina.com
  github: //github.com/hello-me
  # wechat and qq should be a path of qr-code image
  wechat:
  qq:
  weibo: https://weibo.com/5281698833/profile?rightmod=1&wvr=6&mod=personinfo
  zhihu:
  douban:
  facebook:
  twitter:
  instagram:
  stack-overflow:
  v2ex:
  bilibili:
  linkedin:
  others:
  rss:
# friends
friends:
  Vue.js: //cn.vuejs.org/index.html
  React: //reactjs.org/
  friendC:
about:
  enable: true
  image: './intro/about-bg.jpg'

# ========== Site ========== #
# title of the site
SEO_title: hello-me
# main title
main_title:  Do Better
# subtitle
subtitle: 你很自由，充满无限可能，这是很棒的事情
# site haeder image
site_header_image: '/intro/wanzi.jpg'
# post haeder image
post_header_image: '/intro/wanzi.jpg'
# 404 image
_404_image: '/intro/404-bg.jpg'

# ========== Search ========== #
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We did not find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# ========== Comment ========== #
# Fill in the field to enable the corresponding comment plugin
# If you want to add other comment plugin, edit in "custom.ejs"
comment:
  # Livere  site: https://livere.com/
  livere_uid:
  # Disqus  site: https://disqus.com/
  disqus_shortname:
  # Changyan  site: http://changyan.kuaizhan.com/
  changyan_appid:
  changyan_conf:
  # Gitment  site: https://github.com/imsun/gitment
  gitment_owner:
  gitment_repo:
  gitment_client_id:
  gitment_client_secret:
  # Youyan  site: http://www.uyan.cc/
  youyan_uid:

# ========== Analytics ========== #
# enable Busuanzi analytics
busuanzi: true
# fill in pv or uv
busuanzi_pv_or_uv: 'pv'
# custom analytic slogan, '${count}' is the analytic number, DO NOT modify it.
busuanzi_slug: 'PV: ${count} :)'
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /assets/meee.jpg
# truncate length of abstracts in index page (the default is 300, there will be no abstruct if you input 0)
truncate_length: 100
# enable toc
toc: true
# word count & reading time
reading_info: true
# intro height (the default is 50 percents of the screen, you can input other number)
index_intro_height: 50
post_intro_height: 20
about_intro_height: 50
# copyright
copyright:
  enable: true
  # https://creativecommons.org/
  license: '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
